name: FP - Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci #install dependecy
    - run: npx husky install
    - run: npx run lint
    - run: npm run build